# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-11 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('hostel_name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=10)),
                ('mess_number', models.CharField(max_length=50)),
            ],
        ),
    ]
