# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-11 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20180211_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='mess_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='registration',
            name='year',
            field=models.IntegerField(),
        ),
    ]
