# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-20 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20180220_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='time_stamp',
            field=models.DateTimeField(default='YYYY-MM-DD'),
        ),
    ]
