# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-20 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20180220_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='department',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='hostel_name',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='mess_number',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='year',
        ),
        migrations.AlterField(
            model_name='notifications',
            name='time_stamp',
            field=models.DateTimeField(help_text='YYYY-DD-MM'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
