# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-21 10:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_auto_20180320_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 21, 15, 59, 41, 165450)),
        ),
    ]
