# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-21 10:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_auto_20180321_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 21, 16, 24, 37, 271613)),
        ),
    ]
