# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-26 11:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0020_auto_20180326_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='link',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 26, 17, 21, 27, 47438)),
        ),
    ]
