# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-26 13:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0021_auto_20180326_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_us',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('para_1', models.CharField(max_length=1000)),
                ('para_2', models.CharField(max_length=2000)),
                ('hostel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.Hostel_name')),
            ],
        ),
        migrations.CreateModel(
            name='Allotment_scheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme', models.CharField(max_length=1000)),
                ('hostel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.Hostel_name')),
            ],
        ),
        migrations.CreateModel(
            name='Hostel_images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.ImageField(default='default_dp.png', upload_to='media')),
                ('image_2', models.ImageField(default='default_dp.png', upload_to='media')),
                ('image_3', models.ImageField(default='default_dp.png', upload_to='media')),
                ('hostel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.Hostel_name')),
            ],
        ),
        migrations.AlterField(
            model_name='notifications',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 26, 18, 55, 18, 220112)),
        ),
    ]
