# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-05 16:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0023_auto_20180327_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='warden',
            name='warden_email_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='warden',
            name='warden_position',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 5, 21, 33, 13, 170040)),
        ),
    ]
